version: "3.9"

services:
 # ===== DATABASE =====
  mongodb:
    image: mongo:7
    container_name: rent-room-mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: rent_room_db
    volumes:
      - mongo_data:/data/db
 
#  sqlserver:
#    image: mcr.microsoft.com/mssql/server:2022-latest
#    container_name: sqlserver
#    environment:
#      SA_PASSWORD: "12345"
#      ACCEPT_EULA: "Y"
#    ports:
#      - "1433:1433"
#    volumes:
#      - sqlserver_data:/var/opt/mssql

#  # ===== BACKEND =====
#  backend:
#    build: ./backend
#    container_name: rent-room-backend
#    env_file:
#      - .env
#    ports:
#      - "8080:8080"
#    depends_on:
#      - sqlserver

#  # ===== FRONTEND =====
#  frontend:
#    build: ./frontend -- Chưa rõ Tuấn ANh ghi name file sao fix sau
#    container_name: rent-room-frontend
#    ports:
#      - "3000:80"
#    depends_on:
#      - backend

volumes:
    mongo_data:
#  sqlserver_data:
