spring:
  application:
    name: BE

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI}


server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH}

cors:
  urls: ${CORS_URL}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

app:
  cookie:
    secure: false

google:
  client:
    id: ${GOOGLE_ID}
    secret: ${GOOGLE_SECRET}
    uri: ${GOOGLE_URI}